version: '3'
services:
  kerosine-invoice-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: invoice-client:v1
    environment:
      PORT: ${FRONTEND_APP_PORT}
      API_URL: ${API_URL}
      PROXY_API: http://playground-web-backend:8080/
    ports:
      - '${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}'
    container_name: invoice-client
    volumes:
      - ./:/app/frontend
      - /frontend/node_modules
    restart: 'unless-stopped'
    networks:
      - client-network
  kerosine-invoice-backend:
    build:
      context: ./backend
      target: production-build-stage
      dockerfile: Dockerfile
    image: invoice-api:v1
    ports:
      - '${BACKEND_APP_PORT}:${BACKEND_APP_PORT}'
    environment:
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    volumes:
      - ./:/app/backend
      - /backend/node_modules
    restart: 'unless-stopped'
    networks:
      - api-network

networks:
  api-network:
    name: invoice-network
    driver: bridge
  client-network:
    name: invoice-network
    driver: bridge

volumes:
  api-data:
    name: invoice-data
    driver: local
