# Common build stage
FROM node:14.14.0-alpine3.12 as common-build-stage

COPY . ./backend

WORKDIR /backend

RUN npm install typescript -g

RUN npm install pm2 -g

RUN npm install

EXPOSE 3000

# Development build stage
FROM common-build-stage as development-build-stage

ENV NODE_ENV development

CMD ["npm", "run", "deploy:dev"]

# Production build stage
FROM common-build-stage as production-build-stage

ENV NODE_ENV production

CMD ["npm", "run", "deploy:prod"]
